### ISSUE TITLE
User and Password 

### ISSUE THREAD

**Issue by codeskin-r** [dbeley/nixos-config#107]
Hello! First of all, thank you very much for the configuration! I have a noob problem, how should I log in? I can't find my username and password. Thank you! 
![20240702_222201](https://github.com/dbeley/nixos-config/assets/159903896/6946c25f-6bd4-425d-806c-de4a2b041a47)

**Comment by dbeley** [comment]
Hey! For my configuration in particular the main user is configured here: https://github.com/dbeley/nixos-config/blob/main/flake.nix#L82, so if you haven't changed anything you should have a `david` user (and if you haven't changed anything it should have an empty password?).

Otherwise it depends on how you first installed NixOS, normally with a live ISO you should have created a default user, but you might also have a `root` user without a password if you haven't configured anything.
